# Export traces to a Jaeger instance.
#
# Variables:
#
# - $JAEGER_HOST

receivers:
  otlp:
    protocols:
      grpc:
      http:
  fluentforward:
    endpoint: "0.0.0.0:24224"

processors:
  batch:

exporters:
  jaeger:
    # Default Jaeger GRPC server
    endpoint: "$JAEGER_HOST:14250"
    tls:
      insecure: true
  logging:
    logLevel: debug

extensions:
  health_check:
    port: 13133
  zpages:
   endpoint: "0.0.0.0:55679"

service:
  extensions: [health_check,zpages]
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [jaeger,logging]
    logs:
      receivers: [fluentforward]
      # processors: [batch]
      exporters: [logging]

