apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: sg-executor-codeintel-role
  namespace: src-ed654e65e35cf36daa38
rules:
  - apiGroups:
      - batch
    resources:
      - jobs
    verbs:
      - get
      - create
      - delete
  - apiGroups:
      - ""
    resources:
      - pods
      - pods/log
    verbs:
      - get
      - list
      - watch
