apiVersion: apps/v1
kind: Deployment
metadata:
  name: sg-executor
spec:
  selector:
    matchLabels:
      app: sg-executor
  template:
    metadata:
      labels:
        app: sg-executor
    spec:
      hostNetwork: true
      serviceAccountName: sg-executor-service-account
      containers:
        - name: sg-executor
          image: executor-kubernetes:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: EXECUTOR_FRONTEND_URL
              value: http://host.docker.internal:3082
            - name: EXECUTOR_FRONTEND_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: executor-frontend-password
                  key: EXECUTOR_FRONTEND_PASSWORD
            - name: EXECUTOR_QUEUE_NAME
              value: batches
            - name: EXECUTOR_MAXIMUM_NUM_JOBS
              value: "10"
            - name: SRC_LOG_LEVEL
              value: info
            - name: SRC_LOG_FORMAT
              value: condensed
            - name: SRC_TRACE_LOG
              value: "false"
          volumeMounts:
            - mountPath: /data
              name: sg-executor-volume
      volumes:
        - name: sg-executor-volume
          persistentVolumeClaim:
            claimName: sg-executor-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sg-executor-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: sg-executor
  labels:
    app: sg-executor
spec:
  selector:
    app: sg-executor
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  type: LoadBalancer
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sg-executor-service-account
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default
  name: sg-executor-job-role
rules:
  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: ["get", "create", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: sg-executor-log-role
rules:
  - apiGroups: [""]
    resources: ["pods", "pods/log"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: sg-executor-job-role-binding
  namespace: default
subjects:
  - kind: ServiceAccount
    name: sg-executor-service-account
    namespace: default
roleRef:
  kind: Role
  name: sg-executor-job-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: sg-executor-log-role-binding
subjects:
  - kind: ServiceAccount
    name: executor-service-account
roleRef:
  kind: Role
  name: sg-executor-log-role
  apiGroup: rbac.authorization.k8s.io
