apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sg-executor-codeintel-pvc
  namespace: src-ed654e65e35cf36daa38
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
