apiVersion: apps/v1
kind: Deployment
metadata:
  name: executor
spec:
  selector:
    matchLabels:
      app: executor
  template:
    metadata:
      labels:
        app: executor
    spec:
      serviceAccountName: executor-service-account
      containers:
        - name: executor
          image: k8s-exp:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: executor
  labels:
    app: executor
spec:
  selector:
    app: executor
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  type: LoadBalancer
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: executor-service-account
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default
  name: executor-job-role
rules:
  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: ["get", "create", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: executor-log-role
rules:
  - apiGroups: [""]
    resources: ["pods", "pods/log"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: executor-job-role-binding
  namespace: default
subjects:
  - kind: ServiceAccount
    name: executor-service-account
    namespace: default
roleRef:
  kind: Role
  name: executor-job-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: my-log-binding
subjects:
  - kind: ServiceAccount
    name: executor-service-account
roleRef:
  kind: Role
  name: executor-log-role
  apiGroup: rbac.authorization.k8s.io
