name: Cody Review

on:
  pull_request_target:
    types:
      - labeled
      - unlabeled
      - push
    branches:
      - 'tr/**'

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - name: Check for "cody-review" label
        id: check_label
        run: |
          PR_LABEL="${{ github.event.label.name }}"
          TARGET_LABEL="cody-review"
          echo "PR_LABEL=$PR_LABEL"
          if [ "$PR_LABEL" == "$TARGET_LABEL" ]; then
            echo "::set-output name=action::review"
          else
            echo "::set-output name=action::remove_review"
          fi
        shell: bash
