name: Cody Review

on:
  pull_request:
    types:
      - labeled

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - name: Check for "cody-review" label
        if: contains(github.event.pull_request.labels.*.name, 'cody-review')
        run: |
          echo "CODY_REVIEW=true" >> $GITHUB_ENV

      - name: Leave a comment
        if: env.CODY_REVIEW == 'true'
        uses: peter-evans/create-or-update-comment@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            Hi, I'm Cody! I'm starting my review of this PR. I'll leave comments as I go along.
          reactions: 'eyes'

