name: Cody Review

on:
  pull_request:
    types:
      - labeled
      - unlabeled
    branches:
      - tr/cody-review

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - name: Check for "cody-review" label
        if: contains(github.event.pull_request.labels.*.name, 'cody-review')
        run: |
          echo "CODY_REVIEW=true" >> $GITHUB_ENV

      - name: Leave a comment
        if: env.CODY_REVIEW == 'true'
        uses: peter-evans/create-or-update-comment@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            Hi, I'm Cody! I'm starting my review of this PR. I'll leave comments as I go along.
          reactions: 'eyes'

      - name: Remove comment
        if: env.CODY_REVIEW != 'true' && github.event.action == 'unlabeled'
        uses: peter-evans/delete-comment@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          comment-id: ${{ steps.leave-a-comment.outputs.comment-id }}
        run: |
          echo "CODY_REVIEW=false" >> $GITHUB_ENV

      - name: Check out repository
        if: env.CODY_REVIEW == 'true'
        uses: actions/checkout@v2

      - name: Check out repository and install
        if: env.CODY_REVIEW == 'true'
        uses: actions/checkout@v3
        uses: pnpm/action-setup@v2
        id: pnpm-install
        with:
          version: 7.28.0
          run_install: false

      - name: Get pnpm store directory
        if: env.CODY_REVIEW == 'true'
        id: pnpm-cache
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT\

      - name: Setup pnpm cache
        if: env.CODY_REVIEW == 'true'
        uses: actions/cache@v3
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install npm dependencies
        if: env.CODY_REVIEW == 'true'
        run: pnpm install --frozen-lockfile

      - name: Run Cody Review
        if: env.CODY_REVIEW == 'true'
        run: pnpm --filter ./client/cody-review run review
